### ISSUE TITLE
Mechanism for automatically setting up an Attachment Point

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-box#20]
There should be an automatic way to download the necessary scripts for an Attachment point and moving them to the correct directories.
This should also set up a cron job or systemd service that automatically executes the scripts.

**Comment by hausheer** [comment]
As discussed with @juagargi this issue is partially addressed by PR #30 which provides an install script that is primarily targeted at manual installation of an attachment point on infrastructure nodes. 

In addition to that, the goal is that a SCIONLab user can select in the coordinator UI to have his SCION AS setup as an attachment point (this requires that the AS has a public IP). We just need one additional check box in the coordinator UI for this.
